#!/usr/bin/env python3
"""MCP stdio server exposing vernon_project's whitelisted API as tools.

Doesn't import frappe — runs in its own venv, talks to the live site over
its existing HTTP API (same one the mobile/web frontends use). Frappe's own
@frappe.whitelist() + doc-permission checks enforce access, scoped to
whichever user the API key belongs to — no separate authz logic here.

Tool list is generated by statically scanning vernon_project/api/*.py for
@frappe.whitelist() functions (stdlib ast, no frappe import needed), so it
never drifts from the real endpoint set.
"""
import ast
import os
from pathlib import Path

import requests
from mcp.server.mcpserver import MCPServer

API_DIR = Path(__file__).resolve().parent.parent / "vernon_project" / "api"
SITE_URL = os.environ.get("VERNON_SITE_URL", "https://project.vernon.id").rstrip("/")
API_KEY = os.environ.get("VERNON_API_KEY")
API_SECRET = os.environ.get("VERNON_API_SECRET")
PREFIX = "vernon_project.api."

mcp = MCPServer("vernon-project")


def _is_whitelist_decorator(dec: ast.expr) -> bool:
    target = dec.func if isinstance(dec, ast.Call) else dec
    return (
        isinstance(target, ast.Attribute)
        and target.attr == "whitelist"
        and isinstance(target.value, ast.Name)
        and target.value.id == "frappe"
    )


def _signature(node: ast.FunctionDef) -> str:
    a = node.args
    parts = [n.arg for n in a.posonlyargs + a.args[: len(a.args) - len(a.defaults)]]
    for n, d in zip(a.args[len(a.args) - len(a.defaults):], a.defaults):
        parts.append(f"{n.arg}={ast.unparse(d)}")
    if a.vararg:
        parts.append(f"*{a.vararg.arg}")
    for n, d in zip(a.kwonlyargs, a.kw_defaults):
        parts.append(f"{n.arg}={ast.unparse(d)}" if d else n.arg)
    if a.kwarg:
        parts.append(f"**{a.kwarg.arg}")
    return f"{node.name}({', '.join(parts)})"


def _scan() -> list[dict]:
    """Every @frappe.whitelist() function under vernon_project/api/*.py."""
    out = []
    for path in sorted(API_DIR.glob("*.py")):
        module = f"{PREFIX}{path.stem}"
        tree = ast.parse(path.read_text())
        for node in tree.body:
            if not isinstance(node, ast.FunctionDef):
                continue
            if not any(_is_whitelist_decorator(d) for d in node.decorator_list):
                continue
            out.append({
                "method": f"{module}.{node.name}",
                "signature": _signature(node),
                "doc": (ast.get_docstring(node) or "").strip(),
            })
    return out


_MANIFEST = _scan()
_KNOWN = {t["method"] for t in _MANIFEST}


@mcp.tool()
def list_api_methods(search: str = "") -> list[dict]:
    """List vernon_project's whitelisted API methods (dotted path, signature, docstring).

    Optional `search` filters by substring match on method name or docstring
    (case-insensitive). Call this first to find the right method, then
    call_api_method to invoke it.
    """
    if not search:
        return _MANIFEST
    s = search.lower()
    return [t for t in _MANIFEST if s in t["method"].lower() or s in t["doc"].lower()]


@mcp.tool()
def call_api_method(method: str, kwargs: dict | None = None) -> dict:
    """Call one vernon_project.api.* whitelisted method on the live site.

    `method` must be a dotted path from list_api_methods, e.g.
    "vernon_project.api.food_invite.get_pending_invites". `kwargs` are passed
    as the method's arguments. Runs as whichever user the configured API key
    belongs to — same permission checks as the real app.
    """
    if method not in _KNOWN:
        raise ValueError(f"{method!r} is not a known vernon_project.api.* whitelisted method — call list_api_methods first")
    if not API_KEY or not API_SECRET:
        raise RuntimeError("VERNON_API_KEY / VERNON_API_SECRET not set in the server environment")

    resp = requests.post(
        f"{SITE_URL}/api/method/{method}",
        json=kwargs or {},
        headers={"Authorization": f"token {API_KEY}:{API_SECRET}"},
        timeout=30,
    )
    try:
        body = resp.json()
    except ValueError:
        resp.raise_for_status()
        raise
    if not resp.ok:
        detail = body.get("_server_messages") or body.get("exception") or body.get("message") or body
        raise RuntimeError(f"{method} -> HTTP {resp.status_code}: {detail}")
    return body.get("message", body)


def _run_http() -> None:
    """Remote transport for claude.ai Connectors — reached via nginx at
    mcp.vernon.id, proxying to 127.0.0.1:VERNON_MCP_PORT. Locked with a
    static token (query param or Bearer header) instead of full OAuth: this
    is a single-user personal server, not a multi-tenant integration, and
    claude.ai just replays the exact URL you paste in, so a token baked into
    the URL is enough. Constant-time compare to avoid timing leaks.
    """
    import hmac

    import uvicorn
    from mcp.server.transport_security import TransportSecuritySettings
    from starlette.responses import PlainTextResponse

    token = os.environ.get("VERNON_MCP_TOKEN")
    if not token:
        raise SystemExit("VERNON_MCP_TOKEN must be set to run the HTTP transport")
    host = os.environ.get("VERNON_MCP_HOST", "mcp.vernon.id")
    port = int(os.environ.get("VERNON_MCP_PORT", "8811"))

    class TokenAuth:
        def __init__(self, app):
            self.app = app

        async def __call__(self, scope, receive, send):
            if scope["type"] != "http":
                return await self.app(scope, receive, send)
            qs = dict(p.split("=", 1) for p in scope.get("query_string", b"").decode().split("&") if "=" in p)
            auth_header = next((v for k, v in scope.get("headers", []) if k == b"authorization"), b"").decode()
            supplied = qs.get("token") or auth_header.removeprefix("Bearer ").strip()
            if not hmac.compare_digest(supplied, token):
                resp = PlainTextResponse("unauthorized", status_code=401)
                return await resp(scope, receive, send)
            return await self.app(scope, receive, send)

    app = mcp.streamable_http_app(
        host="127.0.0.1",
        transport_security=TransportSecuritySettings(allowed_hosts=[host, "127.0.0.1", f"127.0.0.1:{port}"]),
    )
    uvicorn.run(TokenAuth(app), host="127.0.0.1", port=port, log_level="info")


if __name__ == "__main__":
    if os.environ.get("VERNON_MCP_TRANSPORT") == "http":
        _run_http()
    else:
        mcp.run()
